# ===================================================================
# Spring Boot configuration for the "dev" profile.
# Overrides application.yml settings.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.application.myapp: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false
  docker:
    compose:
      enabled: false
      profiles:
        active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/application
    username: application
    password: "@254Appetizer/"
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    contexts: dev
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: false

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ZmZjYjAwN2E2YTY1NWJlZmJkNmJjODkxN2E2MDYyMDAzNzJhNWM1ZmJiNDA1ZWM3NDdiZDIxM2UxOWY5M2ZlMWU0YWUwNzk2ZTYyNGQwMTYwOTQ5MDQ3Y2Q3NzUwNzU0OGRlYzdhZmQ3NWZmNTRiNTk5N2U5MWUwYzQwMjA3ZjI=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
